#!/usr/bin/env node
/**
 * 1xSecret migration runner.
 *
 * Applies the SQL files in ./drizzle (generated by drizzle-kit at development
 * time) in filename order, tracking applied migrations in the
 * `_1xsecret_migrations` table.
 *
 * Safe under concurrency: the whole run holds the session-level advisory lock
 * 745839201701 on a dedicated connection, so any number of parallel runs
 * (docker-compose one-shot service, Helm hook Job, `docker compose up`
 * retries, operators running it manually) serialize cleanly — followers see
 * the migrations as already applied and exit 0.
 *
 * Zero dependencies beyond `pg`, which ships in the production image.
 *
 * Usage: node scripts/migrate.mjs [--dir <migrations-dir>]
 * Env:   DATABASE_URL (required), MIGRATE_LOCK_TIMEOUT_SECONDS (default 300)
 */

import { readdir, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import pg from "pg";

const MIGRATION_LOCK_ID = "745839201701";

function fail(message) {
  console.error(`[migrate] ${message}`);
  process.exit(1);
}

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) fail("DATABASE_URL is required");

const dirFlagIndex = process.argv.indexOf("--dir");
const migrationsDir =
  dirFlagIndex !== -1 && process.argv[dirFlagIndex + 1]
    ? path.resolve(process.argv[dirFlagIndex + 1])
    : path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../drizzle");

const lockTimeoutSeconds = Number(
  process.env.MIGRATE_LOCK_TIMEOUT_SECONDS ?? "300",
);

async function main() {
  let entries;
  try {
    entries = await readdir(migrationsDir);
  } catch {
    fail(`migrations directory not found: ${migrationsDir}`);
  }
  const files = entries.filter((name) => name.endsWith(".sql")).sort();
  if (files.length === 0) fail(`no .sql migrations in ${migrationsDir}`);

  const client = new pg.Client({
    connectionString: databaseUrl,
    connectionTimeoutMillis: 15_000,
  });
  await client.connect();

  try {
    console.log(
      `[migrate] waiting for advisory lock ${MIGRATION_LOCK_ID} (timeout ${lockTimeoutSeconds}s)...`,
    );
    await client.query(`SET lock_timeout = '${lockTimeoutSeconds}s'`);
    await client.query(`SELECT pg_advisory_lock($1)`, [MIGRATION_LOCK_ID]);
    await client.query(`SET lock_timeout = DEFAULT`);
    console.log("[migrate] lock acquired");

    await client.query(`
      CREATE TABLE IF NOT EXISTS _1xsecret_migrations (
        name text PRIMARY KEY,
        hash text NOT NULL,
        applied_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    const { rows: appliedRows } = await client.query(
      `SELECT name, hash FROM _1xsecret_migrations`,
    );
    const applied = new Map(appliedRows.map((row) => [row.name, row.hash]));

    let ran = 0;
    for (const file of files) {
      const sqlText = await readFile(path.join(migrationsDir, file), "utf8");
      const hash = createHash("sha256").update(sqlText).digest("hex");

      const appliedHash = applied.get(file);
      if (appliedHash !== undefined) {
        if (appliedHash !== hash) {
          fail(
            `migration ${file} was already applied with different content ` +
              `(expected hash ${appliedHash}, file is ${hash}); ` +
              `never edit applied migrations — add a new one`,
          );
        }
        continue;
      }

      console.log(`[migrate] applying ${file}...`);
      await client.query("BEGIN");
      try {
        // drizzle-kit separates statements with `--> statement-breakpoint`
        // comments; the simple query protocol executes the batch as-is.
        await client.query(sqlText);
        await client.query(
          `INSERT INTO _1xsecret_migrations (name, hash) VALUES ($1, $2)`,
          [file, hash],
        );
        await client.query("COMMIT");
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      }
      ran += 1;
    }

    console.log(
      ran === 0
        ? `[migrate] up to date (${files.length} migrations already applied)`
        : `[migrate] applied ${ran} migration(s)`,
    );
  } finally {
    // Ending the session releases the advisory lock.
    await client.end().catch(() => {});
  }
}

main().catch((error) => {
  console.error("[migrate] failed:", error);
  process.exit(1);
});
